### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by MathGuthmann** [andbreder/holyrics#1]
the code css its not working in  open broadcast software(OBS).

**Comment by MathGuthmann** [comment]
the font size not working

**Comment by andbreder** [comment]
_ptBR - Salve! man.. só pela brincadeira, vamos lá!_
bro, what's exactly is not working? -- are you a dev? know front-end? we're using this code, at least something similar, on ours transmissions for a long time... one day, maybe, i will release a new version
